version: '3'
services:
  api:
    build: ./
    restart: always
    depends_on:
      - "postgres"
    env_file:
      - .env
    ports:
      - "8000:80"
    networks:
      default:

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      default:
